import { Container, Box, ButtonGroup, Button, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

export default function Home() {
  const route = useRouter();
  const loginBtnOnClick = () => {
    route.push("/login");
  };
  return (
    <Container>
      <Head>
        <title>Pocket Note + </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <Box
          component="img"
          src={"/logo.png"}
          alt="logo"
          sx={{ height: 150, width: "auto" }}
        />
        <Box>
          <Typography fontSize={{ md: 24 }} mt={2} mb={6}>
            PocketNote is a personal notes app which is very easy to manage with
            a very excellent user experience. <br />
            You can also download the app from your browser.
          </Typography>
        </Box>

        <Box sx={{ display: { md: "none" } }}>
          <ButtonGroup>
            <Button
              variant="contained"
              sx={{ width: 100, bgcolor: "#9714E8", textTransform: "none" }}
              onClick={loginBtnOnClick}
            >
              Sign in
            </Button>
            <Button
              sx={{
                width: 100,
                borderColor: "#9714E8",
                color: "#9714E8",
                textTransform: "none",
              }}
            >
              Register
            </Button>
          </ButtonGroup>
          <br />
          <Typography variant="caption">
            You can create a{" "}
            <span style={{ color: "#9714E8" }}>
              <b>Free</b>
            </span>{" "}
            account by clicking on the{" "}
            <span style={{ color: "#9714E8" }}>
              <b>Register</b>
            </span>{" "}
            button. Otherwise, you can{" "}
            <span style={{ color: "#9714E8" }}>
              <b>Sign in</b>
            </span>{" "}
            if you are an existing user.
          </Typography>
        </Box>
      </main>
    </Container>
  );
}
